name: chromalive_tl_24h_380px
path:
data_shape: [3, 256, 256]
transforms:
  _target_: torchvision.transforms.transforms.Compose
  transforms:
  - _target_: torchvision.transforms.transforms.Resize
    size: 256
  - _target_: torchvision.transforms.ConvertImageDtype # this also scales to [0; 1]
    dtype: ${torch_dtype:float32} # passed dtype must be accessible as a "torch" attribute
  - _target_: torchvision.transforms.Normalize
    mean: [0.5, 0.5, 0.5] # move to [-1:1]
    std: [0.5, 0.5, 0.5]
  - _target_: torchvision.transforms.RandomHorizontalFlip
  - _target_: torchvision.transforms.RandomVerticalFlip
  - _target_: GaussianProxy.utils.data.RandomRotationSquareSymmetry
expected_initial_data_range: [0, 255]
expected_dtype: torch.uint8
