name: stat2dyn
channels:
- pytorch
- nvidia
- conda-forge
dependencies:
- conda-forge::python=3.12
- conda-forge::accelerate
- conda-forge::diffusers
- conda-forge::dataclasses
- conda-forge::hydra-core
- conda-forge::hydra-colorlog
- conda-forge::matplotlib
- conda-forge::numpy
- conda-forge::omegaconf
- conda-forge::rich
- conda-forge::submitit
- conda-forge::termcolor
- pytorch::pytorch>=2
- conda-forge::torchinfo
- pytorch::torchvision
- pytorch::pytorch-cuda=12.4
- conda-forge::enlighten
- conda-forge::plotly
- conda-forge::pandas
- conda-forge::pillow
- conda-forge::moviepy
- conda-forge::pre-commit
- conda-forge::jupyter
- conda-forge::ipywidgets
- conda-forge::ipdb
- conda-forge::ruff
- conda-forge::ipympl
- conda-forge::pylint
- conda-forge::tensorboard
- conda-forge::ffmpeg=6
- conda-forge::gitpython
- conda-forge::imageio
- conda-forge::scipy
- pip
- pip:
  - wandb>=0.17.1
  - opencv-python-headless
