name: stat2dyn
channels:
- pytorch
- nvidia
- conda-forge
dependencies:
- conda-forge::python=3.12
- conda-forge::accelerate
- conda-forge::dataclasses
- conda-forge::diffusers
- conda-forge::enlighten
- conda-forge::ffmpeg=6
- conda-forge::gitpython
- conda-forge::hydra-colorlog
- conda-forge::hydra-core
- conda-forge::imageio
- conda-forge::ipdb
- conda-forge::ipympl
- conda-forge::ipywidgets
- conda-forge::jupyter
- conda-forge::matplotlib
- conda-forge::moviepy
- conda-forge::numpy
- conda-forge::omegaconf
- conda-forge::pillow
- conda-forge::pip
- conda-forge::plotly
- conda-forge::pre-commit
- conda-forge::pylint
- pytorch::pytorch>=2
- pytorch::pytorch-cuda=12.4
- conda-forge::pyyaml
- conda-forge::rich
- conda-forge::ruff
- conda-forge::scipy
- conda-forge::seaborn
- conda-forge::submitit
- conda-forge::termcolor
- conda-forge::torchinfo
- pytorch::torchvision
- conda-forge::tqdm
- conda-forge::wandb
- pip:
  - opencv-python-headless
  - -e git+https://github.com/thethomasboyer/torch-fidelity-symlinks.git@master#egg=torch-fidelity --config-settings editable_mode=strict
