name: Ruff Lint

on: [push]

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run Ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: "check --extend-ignore FIX"
        env:
          RUFF_OUTPUT_FORMAT: github
